apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: acme-todo
  labels:
    app: frontend
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: acme-todo
  labels:
    app: backend
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
  namespace: acme-todo
  labels:
    app: database
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: acme-todo
  labels:
    app: prometheus
automountServiceAccountToken: true
